import { drizzleAdapter } from "@better-auth/drizzle-adapter";
import { parseEnv, webEnvSchema } from "@issuefit/config";
import { accounts, sessions, users, verifications } from "@issuefit/database";
import { betterAuth } from "better-auth";

import { getDb } from "./db";
import { mapGithubProfileToUser } from "./github-profile";

function createAuth() {
  const env = parseEnv(webEnvSchema, process.env);
  const db = getDb();

  return betterAuth({
    baseURL: env.BETTER_AUTH_URL,
    secret: env.BETTER_AUTH_SECRET,
    database: drizzleAdapter(db, {
      provider: "pg",
      // Keys must match the modelName settings below — the adapter resolves
      // the model name first, then looks it up in this schema object.
      schema: {
        users,
        sessions,
        accounts,
        verifications,
      },
    }),
    advanced: {
      database: {
        // Primary keys are uuids generated by PostgreSQL defaults.
        generateId: false,
      },
    },
    user: {
      modelName: "users",
      // No `input: false` here: better-auth strips such fields even when they
      // come from mapProfileToUser, and these columns are NOT NULL. There is
      // no client-controlled signup path that could set them: GitHub social
      // sign-in is the only way to create a user.
      additionalFields: {
        githubUserId: { type: "number", required: false },
        githubUsername: { type: "string", required: false },
      },
    },
    session: { modelName: "sessions" },
    account: { modelName: "accounts" },
    verification: { modelName: "verifications" },
    socialProviders: {
      github: {
        clientId: env.GITHUB_CLIENT_ID,
        clientSecret: env.GITHUB_CLIENT_SECRET,
        mapProfileToUser: mapGithubProfileToUser,
      },
    },
  });
}

let authInstance: ReturnType<typeof createAuth> | null = null;

/**
 * Lazily created so that importing this module (e.g. during `next build`)
 * does not require auth environment variables; they are validated on the
 * first real request instead.
 */
export function getAuth(): ReturnType<typeof createAuth> {
  authInstance ??= createAuth();
  return authInstance;
}
